# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cyoda < Formula
  desc "Lightweight Go EDBMS — digital twin of the Cyoda platform"
  homepage "https://github.com/cyoda-platform/cyoda-go"
  version "0.6.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cyoda-platform/cyoda-go/releases/download/v0.6.1/cyoda_0.6.1_darwin_amd64.tar.gz"
      sha256 "8eb41bf6106f16662a4854caa560e5d38faa63a8326e3e5846f3f8f52761d28c"

      define_method(:install) do
        bin.install "cyoda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cyoda-platform/cyoda-go/releases/download/v0.6.1/cyoda_0.6.1_darwin_arm64.tar.gz"
      sha256 "24277d0f548fe24bb09e7e8fabda16a7ba2dc29b6dd235f73d8c5ecd26752032"

      define_method(:install) do
        bin.install "cyoda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cyoda-platform/cyoda-go/releases/download/v0.6.1/cyoda_0.6.1_linux_amd64.tar.gz"
      sha256 "02b5b3ec471fa05f05c153644a58d6a0325b5257e53f4804f72e938ed4290bbb"
      define_method(:install) do
        bin.install "cyoda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cyoda-platform/cyoda-go/releases/download/v0.6.1/cyoda_0.6.1_linux_arm64.tar.gz"
      sha256 "ef7e470f7a285f897413e37583fbda794708136c7d4d3ad3b3b25119dc6067c4"
      define_method(:install) do
        bin.install "cyoda"
      end
    end
  end

  def post_install
    system bin/"cyoda", "init"
  end

  def caveats
    <<~EOS
      ==============================================================
      cyoda is configured to use sqlite with data stored in
      #{Dir.home}/.local/share/cyoda/cyoda.db

      If you want to reconfigure, run:
        cyoda init --force

      Or set CYODA_STORAGE_BACKEND in your shell environment to
      override the packaged default.
      ==============================================================
    EOS
  end

  test do
    system bin/"cyoda", "--help"
  end
end
