# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cyoda < Formula
  desc "Lightweight Go EDBMS — digital twin of the Cyoda platform"
  homepage "https://github.com/cyoda-platform/cyoda-go"
  version "0.6.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cyoda-platform/cyoda-go/releases/download/v0.6.3/cyoda_0.6.3_darwin_amd64.tar.gz"
      sha256 "019e5b90d62ada79888988affe12446464dc12b773fd6a53b2176b4fa64aba89"

      define_method(:install) do
        bin.install "cyoda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cyoda-platform/cyoda-go/releases/download/v0.6.3/cyoda_0.6.3_darwin_arm64.tar.gz"
      sha256 "3bf0144376abc6b4638d53c052219cc53373edb4ca68f33eedd1679909cb1fe7"

      define_method(:install) do
        bin.install "cyoda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cyoda-platform/cyoda-go/releases/download/v0.6.3/cyoda_0.6.3_linux_amd64.tar.gz"
      sha256 "98b96b685e7de7fcba59f9c709dba7c2b84bced33844845961c00fd31355d56c"
      define_method(:install) do
        bin.install "cyoda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cyoda-platform/cyoda-go/releases/download/v0.6.3/cyoda_0.6.3_linux_arm64.tar.gz"
      sha256 "efbf68e1f4ecf281ac46cccd3c667526f104fcb0e7f3d455bedc06525bd56862"
      define_method(:install) do
        bin.install "cyoda"
      end
    end
  end

  def caveats
    <<~EOS
      ==============================================================
      cyoda is installed but not yet initialised. Run:

        cyoda init

      to write the default sqlite configuration to
      #{Dir.home}/.config/cyoda/ with data stored in
      #{Dir.home}/.local/share/cyoda/cyoda.db.

      Alternatively, set CYODA_STORAGE_BACKEND and related env vars
      in your shell environment to run without an on-disk config.
      ==============================================================
    EOS
  end

  test do
    system bin/"cyoda", "--help"
  end
end
